"""
Code Sus - AI Agent Service
============================
Built with Railtracks (https://railtownai.github.io/railtracks/)

This service uses the Railtracks agentic framework to power the AI features
of the Code Sus game. It follows the patterns from the hackathon quickstart:

  Section 2: rt.agent_node() + await rt.call()       -> Core agent creation
  Section 3: @rt.function_node                        -> Tool creation
  Section 4: output_schema (Pydantic)                 -> Structured output
  Section 5: Multi-agent composition                  -> Agent teams
  Section 6: LLM agnostic (GeminiLLM)                 -> Free Gemini model

Hackathon Challenge Coverage:
  Base:   Custom agents with @rt.function_node tools
  Silver: Pydantic structured output (output_schema=...)
  Gold:   2+ composed agents (Task Generator + Imposter Advisor + Code Verifier)
"""

import os
import json
import asyncio
import logging
import traceback
from typing import List, Literal, Optional
from contextlib import asynccontextmanager

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("code-sus-agent")

from dotenv import load_dotenv
load_dotenv()

from pydantic import BaseModel, Field
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import railtracks as rt

# ═══════════════════════════════════════════════════════════════════════════════
#  PYDANTIC MODELS — Structured Output (Hackathon Section 4)
# ═══════════════════════════════════════════════════════════════════════════════

class CodingTask(BaseModel):
    """An OOP coding task generated by AI for codemates to solve."""
    title: str = Field(description="Short task title, e.g. 'Fix the Inheritance Chain'")
    prompt: str = Field(description="2-3 sentence task description telling the player what to implement or fix")
    starter_code: str = Field(description="Starter code with gaps/bugs for the player to fix. Include comments like // TODO or # TODO to guide the player")
    solution_code: str = Field(description="The fully correct solution code")
    visible_checks: List[str] = Field(description="3 human-readable check descriptions that describe what the code must do")
    validation_patterns: List[str] = Field(description="3 key code fragments that MUST appear in a correct solution, used for automated validation")


class ImposterHint(BaseModel):
    """A single sabotage code suggestion for the imposter."""
    code_snippet: str = Field(description="The full code to replace the current editor contents with. Must be syntactically valid but subtly inefficient or use bad practices")
    bad_practice: str = Field(description="1-2 sentence explanation of why this code is bad practice or inefficient, written as a tip for the imposter")


class ImposterHints(BaseModel):
    """A single sabotage suggestion for a task."""
    hints: List[ImposterHint] = Field(description="Exactly 1 sabotage suggestion with bad-practice code")


class CodeVerification(BaseModel):
    """AI verification result for submitted code."""
    is_correct: bool = Field(description="Whether the code correctly implements the OOP concept described in the task")
    explanation: str = Field(description="1-2 sentence explanation of why the code is correct or what's wrong")
    issues: List[str] = Field(description="List of bad practices or code smells found. Just name the issue, do NOT explain how to fix it. Empty list if code is perfect")
    fixes: List[str] = Field(description="For each issue, a concrete explanation of how to fix it. Same order as issues list. Empty if no issues")


class MeetingInsight(BaseModel):
    """AI-generated discussion points for emergency meetings."""
    suspicious_behaviors: List[str] = Field(description="2-3 observations about potentially suspicious player behavior based on activity data")
    discussion_prompts: List[str] = Field(description="2-3 questions players should discuss during the meeting")
    tip: str = Field(description="A brief strategic tip for the crew")


# ═══════════════════════════════════════════════════════════════════════════════
#  REQUEST MODELS — FastAPI input validation
# ═══════════════════════════════════════════════════════════════════════════════

class GenerateTaskRequest(BaseModel):
    task_type: Literal["inheritance", "polymorphism", "encapsulation"]
    language: str = "javascript"


class ImposterHintsRequest(BaseModel):
    task_type: Literal["inheritance", "polymorphism", "encapsulation"]
    language: str = "javascript"
    current_code: str = ""
    prompt: str = ""


class VerifyCodeRequest(BaseModel):
    task_type: Literal["inheritance", "polymorphism", "encapsulation"]
    language: str = "javascript"
    code: str
    task_prompt: str


class MeetingInsightRequest(BaseModel):
    players: List[dict]
    task_editors: dict = {}
    disruption: int = 0
    task_progress: float = 0.0


# ═══════════════════════════════════════════════════════════════════════════════
#  LLM SETUP — LLM Agnostic (Hackathon Section 6)
# ═══════════════════════════════════════════════════════════════════════════════

# Using free Gemini model — swap to OpenAILLM or AnthropicLLM in one line
llm = rt.llm.GeminiLLM("gemini-2.5-flash")


# ═══════════════════════════════════════════════════════════════════════════════
#  TOOLS — @rt.function_node (Hackathon Section 3)
# ═══════════════════════════════════════════════════════════════════════════════

# Language syntax guides — inlined into system messages to avoid extra API calls.
# Previously these were tool calls, but each tool call doubles the Gemini API
# usage (one call to decide to use the tool, another to process the result).
SYNTAX_GUIDES = {
    "javascript": """JavaScript OOP:
- Class: class Animal { constructor(name) { this.name = name; } speak() { return this.name; } }
- Inheritance: class Dog extends Animal { constructor(name) { super(name); } }
- Private: use #field syntax or closures. Use #balance for private fields.
- Polymorphism: override methods in subclass, no keyword needed""",

    "python": """Python OOP:
- Class: class Animal: def __init__(self, name): self.name = name
- Inheritance: class Dog(Animal): def __init__(self, name): super().__init__(name)
- Private: prefix with underscore _balance (convention) or __balance (name mangling)
- Polymorphism: override methods in subclass, no keyword needed""",

    "java": """Java OOP:
- Class: public class Animal { String name; Animal(String name) { this.name = name; } }
- Inheritance: public class Dog extends Animal { Dog(String name) { super(name); } }
- Private: private int balance; with public getBalance() method
- Polymorphism: @Override annotation, method overriding""",

    "cpp": """C++ OOP:
- Class: class Animal { public: string name; Animal(string name) : name(name) {} };
- Inheritance: class Dog : public Animal { public: Dog(string name) : Animal(name) {} };
- Private: private: section with public getter methods
- Polymorphism: virtual methods, override keyword""",

    "c": """C OOP (struct-based):
- Struct: typedef struct { char* name; } Animal;
- Inheritance: embed base struct: typedef struct { Animal base; } Dog;
- Encapsulation: opaque struct with accessor functions
- Polymorphism: function pointers in struct"""
}


def get_syntax_guide(language: str) -> str:
    """Get OOP syntax reference for a programming language."""
    return SYNTAX_GUIDES.get(language, SYNTAX_GUIDES["javascript"])


@rt.function_node
def validate_code_patterns(code: str, patterns: list) -> dict:
    """Check if code contains all required patterns for task validation.

    Args:
        code (str): The source code to validate.
        patterns (list): List of string patterns that should appear in the code.
    """
    results = []
    for pattern in patterns:
        found = pattern.strip() in code.replace("  ", " ").strip()
        results.append({"pattern": pattern, "found": found})

    all_passed = all(r["found"] for r in results)
    return {
        "passed": all_passed,
        "results": results,
        "summary": "All checks passed." if all_passed else "Some patterns are missing."
    }


# ═══════════════════════════════════════════════════════════════════════════════
#  AGENTS — rt.agent_node (Hackathon Sections 2, 4, 5)
# ═══════════════════════════════════════════════════════════════════════════════

# ── Agent 1: Task Generator (Structured Output — Section 4) ─────────────────
# Syntax guide is injected into prompts dynamically (see endpoints below)
# to avoid extra tool-call API round-trips.
task_generator = rt.agent_node(
    name="OOP Task Generator",
    llm=llm,
    system_message=(
        "You are an expert OOP programming teacher who creates coding challenges "
        "for a multiplayer game. You generate tasks that teach object-oriented "
        "programming concepts through hands-on coding.\n\n"
        "RULES:\n"
        "- Tasks should be solvable in 2-5 minutes\n"
        "- Starter code should have clear TODOs marking what to fix\n"
        "- The solution must be complete and runnable\n"
        "- Validation patterns must be literal code fragments from the solution\n"
        "- Keep code concise (under 30 lines)\n"
        "- Generate DIFFERENT scenarios each time (not always Dog/Animal or BankAccount)\n"
        "- Use creative class names like Vehicle/ElectricCar, Weapon/Sword, Shape/Hexagon, etc.\n"
        "- Visible checks should be written as plain English specs\n"
        "- Validation patterns should be exact code fragments from the solution"
    ),
    output_schema=CodingTask,
)


# ── Agent 2: Imposter Advisor (Structured Output — Section 4) ────────────────
imposter_advisor = rt.agent_node(
    name="Imposter Code Advisor",
    llm=llm,
    system_message=(
        "You are a devious code saboteur for a social deduction game. You generate "
        "ONE code suggestion that looks like a legitimate contribution but uses "
        "bad practices or is subtly inefficient.\n\n"
        "RULES:\n"
        "- The code must be SYNTACTICALLY VALID — it must not cause errors\n"
        "- The code should look plausible to other players watching\n"
        "- Make it SUBTLY bad, not obviously wrong\n"
        "- Strategies: unnecessary complexity, redundant operations, misleading "
        "variable names, overcomplicated logic, anti-patterns, code smells\n"
        "- The code_snippet should be the FULL file content (replacing the editor)\n"
        "- Keep the overall structure recognizable so it looks like real work\n"
        "- The bad_practice field should be a short 1-2 sentence tip explaining "
        "what makes this code inefficient or bad practice (this helps the imposter "
        "understand what they're doing)"
    ),
    output_schema=ImposterHints,
)


# ── Agent 3: Code Verifier (Structured Output + Tool — Sections 3 & 4) ─────
# This agent keeps validate_code_patterns as a @rt.function_node tool
# to satisfy Hackathon Section 3 (Base challenge) requirements.
code_verifier = rt.agent_node(
    name="Code Verifier",
    llm=llm,
    tool_nodes=[validate_code_patterns],
    system_message=(
        "You are a strict code reviewer for an OOP programming game. "
        "You evaluate submitted code for BOTH correctness AND code quality.\n\n"
        "RULES:\n"
        "- Check correctness: does it implement the OOP concept properly?\n"
        "- Check quality: is the code efficient, clean, and following best practices?\n"
        "- Set is_correct to false if the code has ANY of these problems:\n"
        "  * Unnecessary intermediate arrays or data structures\n"
        "  * Redundant loops that could be simplified (e.g. map+loop instead of reduce)\n"
        "  * Overcomplicated logic that does the same thing inefficiently\n"
        "  * Anti-patterns like god objects, deep nesting, misleading names\n"
        "  * Missing or broken OOP concepts (no encapsulation, no polymorphism, etc.)\n"
        "- Even if the code 'works', mark is_correct=false if it uses bad practices\n"
        "- In 'issues': list each bad practice or code smell. Just NAME the problem "
        "(e.g. 'Unnecessary intermediate array in totalArea'). Do NOT explain how to fix.\n"
        "- In 'fixes': for each issue, explain HOW to fix it (shown after the game ends).\n"
        "- Be strict — this is a learning game, catching bad habits is the point"
    ),
    output_schema=CodeVerification,
)


# ── Agent 4: Meeting Analyst (Add-on AI Feature) ────────────────────────────
meeting_analyst = rt.agent_node(
    name="Meeting Behavior Analyst",
    llm=llm,
    system_message=(
        "You are a behavioral analyst for a social deduction game called Code Sus. "
        "During emergency meetings, you analyze player activity data to generate "
        "discussion prompts that help the crew identify the imposter.\n\n"
        "RULES:\n"
        "- NEVER accuse a specific player — only raise observations\n"
        "- Base observations on: who edited which tasks, task completion count, "
        "proximity to sabotage events, editing patterns\n"
        "- Frame observations as questions, not accusations\n"
        "- Keep it fun and game-themed\n"
        "- If data is limited, give general strategic advice"
    ),
    output_schema=MeetingInsight,
)


# ── Coordinator: Game AI Director (Multi-Agent — Section 5) ──────────────────
# This agent delegates to specialists. It is the main entry point.
game_director = rt.agent_node(
    name="Game AI Director",
    llm=llm,
    tool_nodes=[task_generator, imposter_advisor, code_verifier, meeting_analyst],
    system_message=(
        "You are the AI director for Code Sus, a multiplayer OOP learning game. "
        "You coordinate specialist agents to provide game content.\n\n"
        "Your specialists:\n"
        "- OOP Task Generator: Creates coding challenges\n"
        "- Imposter Code Advisor: Generates sabotage suggestions\n"
        "- Code Verifier: Validates code submissions\n"
        "- Meeting Behavior Analyst: Provides meeting discussion points\n\n"
        "Delegate to the appropriate specialist based on the request."
    ),
)


# ═══════════════════════════════════════════════════════════════════════════════
#  FASTAPI SERVICE — HTTP bridge for Node.js server
# ═══════════════════════════════════════════════════════════════════════════════

app = FastAPI(title="Code Sus AI Agent Service", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


async def call_with_retry(agent, prompt, max_retries=2):
    """Call a Railtracks agent with retry logic for rate limit (429) errors."""
    for attempt in range(max_retries + 1):
        try:
            logger.info(f"Calling agent '{agent.name}' (attempt {attempt + 1}/{max_retries + 1})")
            result = await rt.call(agent, prompt)
            logger.info(f"Agent '{agent.name}' returned successfully")
            return result
        except Exception as e:
            error_str = str(e).lower()
            is_rate_limit = "429" in error_str or "rate" in error_str or "quota" in error_str or "resource_exhausted" in error_str
            if is_rate_limit and attempt < max_retries:
                wait_time = 5 * (attempt + 1)  # 5s, 10s
                logger.warning(f"Rate limited on attempt {attempt + 1}. Waiting {wait_time}s before retry...")
                await asyncio.sleep(wait_time)
            else:
                logger.error(f"Agent '{agent.name}' failed: {e}")
                logger.error(traceback.format_exc())
                raise


@app.get("/health")
async def health():
    return {"ok": True, "service": "code-sus-agent", "framework": "railtracks"}


# ── Endpoint 1: Generate a coding task ────────────────────────────────────────
@app.post("/api/generate-task")
async def generate_task(request: GenerateTaskRequest):
    """Generate an AI-powered OOP coding task.

    Uses the Task Generator agent with Pydantic structured output to return
    a fully typed CodingTask object with prompt, starter code, solution, and checks.
    """
    try:
        syntax = get_syntax_guide(request.language)
        prompt = (
            f"Generate a {request.task_type} coding task in {request.language}.\n\n"
            f"Language syntax reference:\n{syntax}\n\n"
            f"The task should teach the concept of {request.task_type} through a "
            f"creative, original scenario (don't use Animal/Dog or BankAccount — "
            f"pick something unique and fun)."
        )

        result = await call_with_retry(task_generator, prompt)
        task = result.structured

        return {
            "ok": True,
            "task": task.model_dump()
        }
    except Exception as e:
        logger.error(f"/api/generate-task failed: {e}")
        return {"ok": False, "error": str(e)}


# ── Endpoint 2: Get imposter sabotage hints ──────────────────────────────────
@app.post("/api/imposter-hints")
async def get_imposter_hints(request: ImposterHintsRequest):
    """Generate 1 sabotage code suggestion for the imposter.

    Uses the Imposter Advisor agent with structured output to return
    a plausible but inefficient/bad-practice code variant.
    """
    try:
        syntax = get_syntax_guide(request.language)
        prompt = (
            f"Generate 1 sabotage suggestion for an {request.task_type} task "
            f"in {request.language}.\n\n"
            f"Language syntax reference:\n{syntax}\n\n"
            f"Task prompt: {request.prompt}\n\n"
            f"Current code in the editor:\n```\n{request.current_code}\n```\n\n"
            f"Generate 1 code variant that looks like real work but uses bad practices "
            f"or is subtly inefficient. The code_snippet should be the full file content. "
            f"The bad_practice should explain in 1-2 sentences why this code is problematic."
        )

        result = await call_with_retry(imposter_advisor, prompt)
        hints = result.structured

        return {
            "ok": True,
            "hints": [h.model_dump() for h in hints.hints]
        }
    except Exception as e:
        logger.error(f"/api/imposter-hints failed: {e}")
        return {"ok": False, "error": str(e)}


# ── Endpoint 3: AI code verification ─────────────────────────────────────────
@app.post("/api/verify-code")
async def verify_code(request: VerifyCodeRequest):
    """AI-powered code review for task submissions.

    Uses the Code Verifier agent to check if submitted code correctly
    implements the OOP concept, providing detailed feedback.
    """
    try:
        prompt = (
            f"Verify this {request.task_type} code in {request.language}.\n\n"
            f"Task: {request.task_prompt}\n\n"
            f"Submitted code:\n```\n{request.code}\n```\n\n"
            f"Does this code correctly implement the {request.task_type} concept? "
            f"Check for proper OOP usage."
        )

        result = await call_with_retry(code_verifier, prompt)
        verification = result.structured

        return {
            "ok": True,
            "verification": verification.model_dump()
        }
    except Exception as e:
        logger.error(f"/api/verify-code failed: {e}")
        return {"ok": False, "error": str(e)}


# ── Endpoint 4: Meeting behavior analysis (Add-on Feature) ──────────────────
@app.post("/api/meeting-insights")
async def meeting_insights(request: MeetingInsightRequest):
    """AI analysis of player behavior for emergency meetings.

    Add-on feature: analyzes who edited what, task progress, and sabotage
    events to generate discussion prompts for the crew.
    """
    try:
        player_summary = "\n".join([
            f"- {p.get('name', 'Unknown')}: "
            f"{'alive' if p.get('isAlive', True) else 'eliminated'}, "
            f"{len(p.get('completedTasks', []))} tasks completed"
            for p in request.players
        ])

        editor_summary = "\n".join([
            f"- Task {tid}: edited by {', '.join(editors)}"
            for tid, editors in request.task_editors.items()
            if editors
        ]) or "No editing data available"

        prompt = (
            f"Analyze this game state for an emergency meeting:\n\n"
            f"Players:\n{player_summary}\n\n"
            f"Task editors:\n{editor_summary}\n\n"
            f"Team progress: {request.task_progress * 100:.0f}%\n"
            f"Sabotage pressure: {request.disruption}/4\n\n"
            f"Generate discussion prompts to help the crew identify the imposter."
        )

        result = await call_with_retry(meeting_analyst, prompt)
        insight = result.structured

        return {
            "ok": True,
            "insight": insight.model_dump()
        }
    except Exception as e:
        logger.error(f"/api/meeting-insights failed: {e}")
        return {"ok": False, "error": str(e)}


# ═══════════════════════════════════════════════════════════════════════════════
#  SERVER ENTRY POINT
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import uvicorn
    print("\n=== Code Sus AI Agent Service ===")
    print("Framework: Railtracks (https://railtownai.github.io/railtracks/)")
    print("LLM: Google Gemini 2.5 Flash (free tier)")
    print("Agents: Task Generator, Imposter Advisor, Code Verifier, Meeting Analyst")
    print("Endpoints:")
    print("  POST /api/generate-task      - Generate AI coding tasks")
    print("  POST /api/imposter-hints     - Get imposter sabotage suggestions")
    print("  POST /api/verify-code        - AI code verification")
    print("  POST /api/meeting-insights   - Meeting behavior analysis")
    print("================================\n")
    uvicorn.run(app, host="0.0.0.0", port=5001)
